import { STEP_DOWN_X, STEP_DOWN_Y, ADMIRE_X, ADMIRE_Y, CLOSE_X, CLOSE_Y } from './mirrorVisitCoords.js'
import { randomPalette } from '../colorUtils.js'

export async function mirrorVisit(engine) {
  const palette = randomPalette()
  await engine.wait(300)
  await engine.moveTo(STEP_DOWN_X, STEP_DOWN_Y, 8)
  await engine.moveTo(ADMIRE_X, STEP_DOWN_Y, 8)
  await engine.moveTo(ADMIRE_X, ADMIRE_Y, 8)
  await engine.face('up')
  await engine.wait(800)
  await engine.moveTo(CLOSE_X, CLOSE_Y, 12)
  await engine.face('up')
  await engine.wait(500)
  await engine.openMirror()
  await engine.wait(600)
  await engine.changeColor('hair',   palette.hair)
  await engine.changeColor('outfit', palette.outfit)
  await engine.changeColor('eyes',   palette.eyes)
  await engine.wait(800)
  await engine.scrollEditor(1)
  await engine.wait(1500)
  await engine.scrollEditor(0)
  await engine.wait(600)
  await engine.closeMirror()
  await engine.wait(400)
  await engine.moveTo(ADMIRE_X, ADMIRE_Y, 12)
  await engine.face('up')
  await engine.wait(1500)
}
