export const TRANSIT_NATAL_LINES = {
  'Sun:Conjunction:Sun':       "The Sun returns to your birth position — a solar return. New intentions set now carry unusual power.",
  'Sun:Conjunction:Moon':      "Your sense of purpose illuminates your emotional core today. Inner and outer life align.",
  'Sun:Trine:Moon':            "Vitality and feeling move in easy harmony. A good day to act on what your heart already knows.",
  'Sun:Square:Moon':           "Tension between who you are becoming and your deep instincts asks for honest reflection.",
  'Sun:Conjunction:Venus':     "Warmth and beauty flow to you effortlessly. Love and creative work are especially favoured.",
  'Sun:Trine:Mars':            "Your will and your natal drive align — energy is high, action comes with confidence.",
  'Sun:Square:Mars':           "Friction between the current solar energy and your natal drive. Channel it, don't suppress it.",
  'Sun:Conjunction:Jupiter':   "A moment of expansion and grace. Something you've been building gains visibility.",
  'Sun:Square:Saturn':         "The present asks more of you than feels comfortable. The effort you make now endures.",
  'Moon:Conjunction:Moon':     "The Moon returns to your natal position — emotions run deep and true today.",
  'Moon:Conjunction:Sun':      "Your emotional tides illuminate your core identity. Feelings are a reliable guide now.",
  'Moon:Trine:Venus':          "Warmth and tenderness arise naturally. Connections made today carry real depth.",
  'Moon:Square:Mars':          "Impulse and instinct collide. Pause before letting raw feeling drive action.",
  'Moon:Conjunction:Saturn':   "A sober mood settles in. Old responsibilities resurface — face them with patience.",
  'Venus:Conjunction:Sun':     "Grace moves through your sense of self. Others are drawn to your presence today.",
  'Venus:Trine:Mars':          "Desire and beauty work together. Creative and romantic energy flows easily.",
  'Venus:Square:Saturn':       "Love and pleasure meet resistance or delay. Patience is its own form of devotion.",
  'Venus:Conjunction:Venus':   "Venus returns to her natal place in your chart — a day charged with beauty and feeling.",
  'Mars:Conjunction:Sun':      "A surge of vitality activates your natal purpose. Act boldly on what matters most.",
  'Mars:Square:Moon':          "Drive and instinct are at odds. Act, but check the impulse before it becomes a wound.",
  'Mars:Trine:Mars':           "Your natal will is energised and flowing. This is a time to push forward with confidence.",
  'Mars:Square:Saturn':        "Effort meets a wall. Patience and strategy will outlast force here.",
  'Jupiter:Conjunction:Sun':   "A season of expansion opens around your core self. Aim higher than you think you can reach.",
  'Jupiter:Trine:Moon':        "Optimism lifts the tides of feeling. Trust the larger arc of where your life is moving.",
  'Jupiter:Conjunction:Venus': "Abundance and affection multiply. Receive without guilt — this is a genuine opening.",
  'Jupiter:Square:Saturn':     "Growth strains against your natal structures. What no longer fits must give way.",
  'Saturn:Conjunction:Sun':    "Saturn tests your identity and purpose. This is a defining season — what survives is real.",
  'Saturn:Square:Moon':        "Emotional weight presses down. Old patterns that no longer serve ask to be released.",
  'Saturn:Return:Saturn':      "Saturn completes its cycle and returns. A major life reckoning — who have you become?",
  'Saturn:Trine:Saturn':       "The structures you have built are affirmed. Steady effort is paying its quiet dividend.",
}
