export { SS00_FLOOR } from './SS00_FLOOR.js'
export { SS01_WALL } from './SS01_WALL.js'
export { SS02_MIRROR } from './SS02_MIRROR.js'
export { SS03_TABLE } from './SS03_TABLE.js'
export { SS04_TORCH } from './SS04_TORCH.js'
export { SS05_DOOR } from './SS05_DOOR.js'
